### ISSUE TITLE
Rules set with severity=ignore are still shown in codacy

### ISSUE THREAD

**Issue by m0rtalis** [codacy/codacy-checkstyle#33]
I have the following rule in my `checkstyle.xml`:
```
<module name="WriteTag">
     <property name="tag" value="@author"/>
     <property name="tagFormat" value="\S"/>
      <property name="severity" value="ignore"/>
     <property name="tagSeverity" value="warning"/>
     <message key="javadoc.writeTag" value="{0} tag is not allowed"/>
</module>
```
according to the [description](http://checkstyle.sourceforge.net/config_javadoc.html#WriteTag) this sets the error message: "Type Javadoc comment is missing {0} tag." to ignore. It still appears in the codacy issues:
![image](https://user-images.githubusercontent.com/20595780/46750480-552f1d80-ccb8-11e8-8d6b-eac3816fe99a.png)
Neither running checkstyle from the commandline or via maven plugin produces those warnings. There only the correct warning `@author tag is not allowed [WriteTag]`

Is the severity=ignore maybe ignored by codacy?

**Comment by rtfpessoa** [comment]
@m0rtalis Codacy does pot perform any logic regarding configuration files. If you are using it, it means Checkstyle is returning that issue since it is managing the file.

To be able to check the specific project please report this issue through the app or to `support at codacy dot com`.

The issue might be that we need to ignore the severities if they are level `ignored` but it is important to check the project first.

**Comment by rtfpessoa** [comment]
Let me know if we need to re-open this.
