### ISSUE TITLE
Checkstyle does not find warnings but should find 4

### ISSUE THREAD

**Issue by uhafner** [codacy/codacy-checkstyle#52]
In my project [uhafner/warnings-ng-plugin](https://app.codacy.com/manual/uhafner/warnings-ng-plugin) your checker does not find CheckStyle warnings anymore. The checker is activated to use a project provided configuration file. Maybe it is picking the wrong one? Is there a way to specify that file? 

In another build that runs CheckStyle with maven I get 4 warnings:
[Jenkins CheckStyle Results](https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/codacy-checkstyle/2/checkstyle/)

**Comment by mrfyda** [comment]
> Property 'allowMissingPropertyJavadoc' does not exist

https://checkstyle.org/releasenotes.html#Release_8.25

The property was removed in 8.25 (Codacy is now running 8.26) as the functionality was moved to a new check, MissingJavadocMethodCheck, in 8.20. Since it was moved, the original check just kept the property to not break configuration and be deprecated. It was now removed.

I suggest you add MissingJavadocMethodCheck to continue the same behavior as before.
